# Parameters for martin-binance strategy
# Copyright © 2021-2025 Jerry Fedorenko aka VM
# __version__ = "3.0.17"


# List exchanges names, don't remove or edit row, add only!
# Accounts name would be identically accounts.name from exchanges-wrapper
exchange = [
   'Demo - Binance',   # 0
   'Demo - OKX',       # 1
   "Demo - Bitfinex",  # 2
   "Demo - Bybit",     # 3
   "Binance",          # 4
   "OKX",              # 5
   "Bitfinex",         # 6
   "Huobi",            # 7
   "Binance US",       # 8
   "Bybit",            # 9
]

[Exporter]
port = 8000
sleep_time_s = 60
vps_name = "**** Place VPS Name there ****"
# CoinMarketCap
url = "https://pro-api.coinmarketcap.com/v2/tools/price-conversion"
api = "********** Place API key for CoinMarketCap there ***********"
rate_limit = 30  # Requests per minute

[Telegram]
tlg_url = "https://api.telegram.org/bot"
tlg_proxy_host = "aaa.bbb.ccc.ddd"  # IP Proxy for Telegram
tlg_proxy_port = 50061
chat_id = "*** Place channel_id there ***"
heartbeat = 10  # sec

   [[Bots]]
   id_exchange = [0, 4, 8]  # 'Binance', 'Demo - Binance', 'Binance US'
   token = "********** Place Token for Telegram bot there ***********"

   [[Bots]]
   id_exchange = [1, 5]  # 'Demo - OKEX', 'OKEX'
   token = "********** Place Token for Telegram bot there ***********"

   [[Bots]]
   id_exchange = [2, 6]  # "Demo - Bitfinex", "Bitfinex"
   token = "********** Place Token for Telegram bot there ***********"

   [[Bots]]
   id_exchange = [3, 9]  # "Demo - Bitfinex", "Bitfinex"
   token = "********** Place Token for Telegram bot there ***********"
