# Parameters for martin-binance strategy
# Copyright © 2021 Jerry Fedorenko aka VM
# __version__ = "1.2.13"

telegram_url = "https://api.telegram.org/bot"

# List exchanges names, don"t remove or edit row, add only!
# If you want reorganize list, clear funds_rate.db before
# Accounts name wold be identically accounts.name from exchanges_wrapper/exch_srv_cfg.toml
exchange = [
   'Demo - Binance',   # 0
   'Demo - OKX',       # 1
   "Demo - Bitfinex",  # 2
   "Demo - Bybit",     # 3
   "Binance",          # 4
   "OKX",              # 5
   "Bitfinex",         # 6
   "Huobi",            # 7
   "Binance US",       # 8
   "Bybit",            # 9
]

[Exporter]
port = 8000
sleep_time_s = 60
vps_name = "**** Place VPS Name there ****"
# CoinMarketCap
url = "https://pro-api.coinmarketcap.com/v2/tools/price-conversion"
api = "********** Place API key for CoinMarketCap there ***********"
rate_limit = 30  # Requests per minute

[[Telegram]]
id_exchange = [0, 4, 8]  # 'Binance', 'Demo - Binance', 'Binance US'
token = "********** Place Token for Telegram bot there ***********"
channel_id = "*** Place channel_id there ***"
inline = true

[[Telegram]]
id_exchange = [1, 5]  # 'Demo - OKEX', 'OKEX'
token = "********** Place Token for Telegram bot there ***********"
channel_id = "*** Place channel_id there ***"
inline = false

[[Telegram]]
id_exchange = [2, 6]  # "Demo - Bitfinex", "Bitfinex"
token = "********** Place Token for Telegram bot there ***********"
channel_id = "*** Place channel_id there ***"
inline = false

[[Telegram]]
id_exchange = [3, 9]  # "Demo - Bitfinex", "Bitfinex"
token = "********** Place Token for Telegram bot there ***********"
channel_id = "*** Place channel_id there ***"
inline = false
