{
 "title": "Crypto exporter",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "v_vps_name", "label": "vps_name", "query": { "query": "label_values(vps_name)" } },
   {
    "name": "v_exchange",
    "label": "Exchange",
    "query": {
     "query": "label_values({vps_name=~\"$v_vps_name\"},exchange)"
    }
   },
   {
    "name": "v_pair",
    "label": "Pair:",
    "query": {
     "query": "label_values({exchange=~\"$v_exchange\"},pair)"
    }
   },
   {
    "name": "v_currency",
    "label": "currency",
    "query": {
     "query": "label_values({exchange=~\"$v_exchange\"}, currency)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Consolidated asset valuation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Assets",
   "type": "piechart",
   "gridPos": { "h": 18, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "margin_balance_usd{currency=~\"$v_currency\",exchange=~\"$v_exchange\"}",
     "legendFormat": "{{currency}} {{exchange}}"
    }
   ]
  },
  {
   "title": "Assets",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 19, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "targets": [
    {
     "expr": "margin_balance_usd{currency=~\"$v_currency\",exchange=~\"$v_exchange\"}",
     "legendFormat": "{{currency}} {{exchange}}"
    },
    {
     "expr": "sum(margin_balance_usd{currency=~\"$v_currency\",exchange=~\"$v_exchange\"})",
     "legendFormat": "USD"
    }
   ]
  },
  {
   "title": "Profit timeline",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "idelta(margin_sum_profit{pair=~\"$v_pair\",exchange=~\"$v_exchange\",vps_name=~\"$v_vps_name\"}[24h:1h]) / margin_last_rate_usd{pair=~\"$v_pair\",exchange=~\"$v_exchange\",vps_name=~\"$v_vps_name\"}",
     "legendFormat": "{{pair}}"
    }
   ]
  },
  {
   "title": "Total profit in USD",
   "type": "stat",
   "gridPos": { "h": 12, "w": 3, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(margin_sum_profit_usd{pair=~\"$v_pair\",exchange=~\"$v_exchange\",vps_name=~\"$v_vps_name\"})",
     "legendFormat": " {{exchange}} {{pair}}"
    }
   ]
  },
  {
   "title": "Profit in USD by trade pair",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 21, "x": 3, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "sum(margin_sum_profit_usd{pair=~\"$v_pair\",exchange=~\"$v_exchange\",vps_name=~\"$v_vps_name\"})",
     "legendFormat": "Total for period"
    },
    {
     "expr": "margin_sum_profit_usd{pair=~\"$v_pair\",exchange=~\"$v_exchange\",vps_name=~\"$v_vps_name\"}",
     "legendFormat": " {{exchange}} {{pair}}"
    }
   ]
  },
  {
   "title": "VPS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "percentunit", "label": "cpu" }
     ],
     "targets": [
      {
       "expr": "margin_vps_cpu{vps_name=~\"$v_vps_name\"}",
       "legendFormat": "{{vps_name}} cpu"
      }
     ]
    },
    {
     "title": "Memory use",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "margin_vps_memory{vps_name=~\"$v_vps_name\"}",
       "legendFormat": "{{vps_name}} mem"
      }
     ]
    }
   ]
  },
  {
   "title": "Trade cycle detail (want be selected one pair only)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cycle count",
     "type": "stat",
     "gridPos": { "h": 8, "w": 2, "x": 0, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "margin_cycle_count{pair=~\"$v_pair\",exchange=~\"$v_exchange\"}",
       "legendFormat": "Total"
      },
      {
       "expr": "margin_buy_count{pair=~\"$v_pair\",exchange=~\"$v_exchange\"}",
       "legendFormat": "Buy"
      },
      {
       "expr": "margin_sell_count{pair=~\"$v_pair\",exchange=~\"$v_exchange\"}",
       "legendFormat": "Sell"
      }
     ]
    },
    {
     "title": "--> $v_pair",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 2, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
     "targets": [
      {
       "expr": "margin_f_balance{pair=~\"$v_pair\",exchange=~\"$v_exchange\",vps_name=~\"$v_vps_name\"}",
       "legendFormat": "Amount"
      },
      {
       "expr": "margin_f_profit{pair=~\"$v_pair\",exchange=~\"$v_exchange\",vps_name=~\"$v_vps_name\"}",
       "legendFormat": "Profit"
      }
     ]
    },
    {
     "title": "$v_pair<--",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 11, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "margin_s_balance{pair=~\"$v_pair\",exchange=~\"$v_exchange\",vps_name=~\"$v_vps_name\"}",
       "legendFormat": "Amount"
      },
      {
       "expr": "margin_s_profit{pair=~\"$v_pair\",exchange=~\"$v_exchange\",vps_name=~\"$v_vps_name\"}",
       "legendFormat": "Profit"
      },
      {
       "expr": "margin_sum_profit{pair=~\"$v_pair\",exchange=~\"$v_exchange\",vps_name=~\"$v_vps_name\"}",
       "legendFormat": "Sum profit by last rate"
      }
     ]
    },
    {
     "title": "Interest for all time",
     "type": "stat",
     "gridPos": { "h": 13, "w": 4, "x": 20, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "margin_buy_interest{pair=~\"$v_pair\",exchange=~\"$v_exchange\",vps_name=~\"$v_vps_name\"}",
       "legendFormat": "Buy interest"
      },
      {
       "expr": "margin_sell_interest{pair=~\"$v_pair\",exchange=~\"$v_exchange\",vps_name=~\"$v_vps_name\"}",
       "legendFormat": "Sell interest"
      },
      {
       "expr": "margin_buy_time{pair=~\"$v_pair\",exchange=~\"$v_exchange\",vps_name=~\"$v_vps_name\"}",
       "legendFormat": "Buy time"
      },
      {
       "expr": "margin_sell_time{pair=~\"$v_pair\",exchange=~\"$v_exchange\",vps_name=~\"$v_vps_name\"}",
       "legendFormat": "Sell time"
      },
      {
       "expr": "86400 * margin_buy_interest{pair=~\"$v_pair\",exchange=~\"$v_exchange\",vps_name=~\"$v_vps_name\"} / margin_buy_time{pair=~\"$v_pair\",exchange=~\"$v_exchange\",vps_name=~\"$v_vps_name\"}",
       "legendFormat": "Avg Buy interest for 24h"
      },
      {
       "expr": "86400 * margin_sell_interest{pair=~\"$v_pair\",exchange=~\"$v_exchange\",vps_name=~\"$v_vps_name\"} / margin_sell_time{pair=~\"$v_pair\",exchange=~\"$v_exchange\",vps_name=~\"$v_vps_name\"}",
       "legendFormat": "Avg Sell interest for 24h"
      },
      {
       "expr": "31536000 * margin_buy_interest{pair=~\"$v_pair\",exchange=~\"$v_exchange\",vps_name=~\"$v_vps_name\"} / margin_buy_time{pair=~\"$v_pair\",exchange=~\"$v_exchange\",vps_name=~\"$v_vps_name\"}",
       "legendFormat": "Forecast APY Buy"
      },
      {
       "expr": "31536000 * margin_sell_interest{pair=~\"$v_pair\",exchange=~\"$v_exchange\",vps_name=~\"$v_vps_name\"} / margin_sell_time{pair=~\"$v_pair\",exchange=~\"$v_exchange\",vps_name=~\"$v_vps_name\"}",
       "legendFormat": "Forecast APY Sell"
      }
     ]
    },
    {
     "title": "Summary amount ($v_pair<--)",
     "type": "timeseries",
     "description": "Total amount for both currency by last rate",
     "gridPos": { "h": 5, "w": 20, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "margin_balance{pair=~\"$v_pair\",exchange=~\"$v_exchange\",vps_name=~\"$v_vps_name\"}",
       "legendFormat": "value"
      }
     ]
    },
    {
     "title": "Cycle parameters ($v_pair)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "margin_f_depo{pair=~\"$v_pair\",exchange=~\"$v_exchange\",vps_name=~\"$v_vps_name\"}",
       "legendFormat": "First depo"
      },
      {
       "expr": "margin_s_depo{pair=~\"$v_pair\",exchange=~\"$v_exchange\",vps_name=~\"$v_vps_name\"}",
       "legendFormat": "Second depo"
      },
      {
       "expr": "margin_cycle_buy{pair=~\"$v_pair\",exchange=~\"$v_exchange\",vps_name=~\"$v_vps_name\"}",
       "legendFormat": "Buy/Sell"
      },
      {
       "expr": "margin_over_price{pair=~\"$v_pair\",exchange=~\"$v_exchange\",vps_name=~\"$v_vps_name\"}",
       "legendFormat": "Over price"
      },
      {
       "expr": "margin_last_rate{pair=~\"$v_pair\",exchange=~\"$v_exchange\",vps_name=~\"$v_vps_name\"}",
       "legendFormat": "Rate"
      }
     ]
    }
   ]
  }
 ]
}